
CREATE DATABASE OPTUS;
GO

USE OPTUS;
GO

CREATE TABLE ARTISTA (
	idArtista SMALLINT PRIMARY KEY IDENTITY(1,1),
	nomeArtista VARCHAR(20) NOT NULL
);
GO

CREATE TABLE ESTILO (
	idEstilo TINYINT PRIMARY KEY IDENTITY(1,1),
	nomeEstilo VARCHAR(20) NOT NULL
);
GO

CREATE TABLE ALBUM(
	idAlbum SMALLINT PRIMARY KEY IDENTITY(1,1),
	idArtista SMALLINT FOREIGN KEY REFERENCES ARTISTA(idArtista),
	nomeAlbum VARCHAR(20) NOT NULL,
	localizacao VARCHAR(60) NOT NULL,
	duracaoAlbum TIME NOT NULL,
	estadoAlbum VARCHAR(7) NOT NULL
);
GO

CREATE TABLE GERENCIAMENTO(
	idGERENCIAMENTO INT PRIMARY KEY IDENTITY(1,1),
	idEstilo TINYINT FOREIGN KEY REFERENCES ESTILO(idEstilo),
	idAlbum SMALLINT FOREIGN KEY REFERENCES ALBUM(idAlbum),
	dataGravacao SMALLDATETIME NOT NULL
);
GO

ALTER TABLE ALBUM
ADD estadoAlbum VARCHAR(7) NOT NULL


CREATE TABLE PERMISSAO (
	idPermissao SMALLINT PRIMARY KEY IDENTITY(1,1),
	tipoPermissao VARCHAR(13) NOT NULL
);
GO

CREATE TABLE USUARIO (
	idUsuario SMALLINT PRIMARY KEY IDENTITY(1,1),
	idPermissao SMALLINT FOREIGN KEY REFERENCES PERMISSAO(idPermissao),
	nomeUsuario VARCHAR(20) NOT NULL,
	emailUsuario VARCHAR (265) NOT NULL,
	senhaUsuario VARCHAR (265) NOT NULL
);
GO

CREATE TABLE CONSULTA (
	idConsulta INT PRIMARY KEY IDENTITY (1,1),
	idUsuario SMALLINT FOREIGN KEY REFERENCES USUARIO(idUsuario),
	idGerenciamento INT FOREIGN KEY REFERENCES GERENCIAMENTO(idGerenciamento),
	dataConsulta SMALLDATETIME NOT NULL
);
GO

--ALTER TABLE CONSULTA
--DROP COLUMN dataConsulta

--ALTER TABLE CONSULTA
--ADD dataConsulta SMALLDATETIME NOT NULL