
CREATE DATABASE EMPRESA;
GO

USE EMPRESA;
GO

CREATE TABLE PESSOA (
	idPessoa SMALLINT PRIMARY KEY IDENTITY(1,1),
	nomePessoa VARCHAR(20) NOT NULL
);

CREATE TABLE TELEFONE (
	idTelefone INT PRIMARY KEY IDENTITY(1,1),
	idPessoa SMALLINT FOREIGN KEY REFERENCES PESSOA(idPessoa),
	numTelefone CHAR(15) NOT NULL UNIQUE
);
GO

/*ALTER TABLE TELEFONE
DROP COLUMN numTelefone

ALTER TABLE TELEFONE
ADD numTelefone CHAR(15) NOT NULL UNIQUE
*/

CREATE TABLE EMAIL (
	idEmail INT PRIMARY KEY IDENTITY(1,1),
	idPessoa SMALLINT FOREIGN KEY REFERENCES PESSOA(idPessoa),
	endEmail VARCHAR(256) NOT NULL UNIQUE
);
GO

CREATE TABLE CNH (
	idCNH SMALLINT PRIMARY KEY IDENTITY(1,1),
	idPessoa SMALLINT FOREIGN KEY REFERENCES PESSOA(idPessoa),
	numCNH CHAR(11) NOT NULL UNIQUE
);
GO