
CREATE DATABASE PCLINICS;
GO

USE PCLINICS;
GO

CREATE TABLE CLINICA (
	idClinica TINYINT PRIMARY KEY IDENTITY(1,1),
	nomeClinica VARCHAR(20) NOT NULL
);
GO

CREATE TABLE VETERINARIO (
	idVeterinario TINYINT PRIMARY KEY IDENTITY(1,1),
	idClinica TINYINT FOREIGN KEY REFERENCES CLINICA(idClinica),
	nomeVet VARCHAR(20) NOT NULL
	CRMV VARCHAR(10) NOT NULL
);
GO

ALTER TABLE VETERINARIO
DROP COLUMN CMRV

ALTER TABLE VETERINARIO
ADD CRMV VARCHAR(10) NOT NULL

/*
ALTER TABLE VETERINARIO
ADD CMRV VARCHAR(10) NOT NULL
*/

CREATE TABLE DONO (
	idDono SMALLINT PRIMARY KEY IDENTITY(1,1),
	nomeDono VARCHAR(20) NOT NULL
);
GO

CREATE TABLE TIPOPET (
	idTipoPet SMALLINT PRIMARY KEY IDENTITY(1,1),
	nomeTipoPet VARCHAR (20) NOT NULL
);
GO

CREATE TABLE RACA (
	idRaca TINYINT PRIMARY KEY IDENTITY(1,1),
	idTipoPet SMALLINT FOREIGN KEY REFERENCES TIPOPET(idTipoPet),
	nomeRaca VARCHAR (20) NOT NULL
);
GO

CREATE TABLE PET (
	idPet INT PRIMARY KEY IDENTITY(1,1),
	idRaca TINYINT FOREIGN KEY REFERENCES RACA(idRaca),
	idDono SMALLINT FOREIGN KEY REFERENCES DONO(idDono),
	nomePet VARCHAR (20) NOT NULL
);
GO

CREATE TABLE ATENDIMENTO (
	idAtendimento INT PRIMARY KEY IDENTITY(1,1),
	idVeterinario TINYINT FOREIGN KEY REFERENCES VETERINARIO(idVeterinario),
	idPet INT FOREIGN KEY REFERENCES PET(idPet),
	descricaoConsulta VARCHAR (50) NOT NULL
	dataConsulta SMALLDATETIME NOT NULL
	custoAtendimento SMALLMONEY NOT NULL
);
GO

/*
ALTER TABLE ATENDIMENTO
DROP COLUMN descriçãoConsulta

ALTER TABLE ATENDIMENTO
ADD descricaoConsulta VARCHAR (50) NOT NULL
*/

/*ALTER TABLE ATENDIMENTO
DROP COLUMN Valor

ALTER TABLE ATENDIMENTO
ADD custoAtendimento SMALLMONEY NOT NULL
*/

