--CRIA UM BANCO DE DADOS CHAMADO CATALOGO.
CREATE DATABASE CATALOGO;
GO 

--DEFINE O BANCO DE DADS QUE SERÁ UTILIZADO
USE CATALOGO;
GO

CREATE TABLE GENERO (
	idGenero TINYINT PRIMARY KEY IDENTITY(1,1),
	nomeGenero VARCHAR(20) NOT NULL
);
GO

CREATE TABLE FILME(
	idFilme SMALLINT PRIMARY KEY IDENTITY(1,1),
	idGenero TINYINT FOREIGN KEY REFERENCES GENERO(idGenero),
	tituloFilme VARCHAR(50) NOT NULL
);